version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./docker/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx
      - .:/var/www/html
    ports:
      - "8080:80"
    links:
      - php

  php:
    build:
      context: ./docker
      dockerfile: php.df
      args:
        - DOCKER_PHP_UID=$DOCKER_PHP_UID
    environment:
      - PHP_IDE_CONFIG=$DOCKER_PHP_IDE_CONFIG
    volumes:
      - ./docker/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - app-sync:/var/www/html
    expose:
      - "9000"
    links:
      - pgsql
    command: "php-fpm -F --allow-to-run-as-root"

  pgsql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_DATABASE
volumes:
  app-sync:
    external: true
